site_name: "Install Guide for XYZ application"
site_description: "Contains instructions for installation of XYZ tool for developers wishing to use it for development."
docs_dir: "docs"
repo_url:  ""
edit_uri: edit/main/docs/
plugins:
    - techdocs-core
    - ezlinks
markdown_extensions:
    - markdown_inline_mermaid
    - md_in_html
    -   mkpatcher:
            location: patcher.py
